### PR TITLE
mlox_base updates and fixes july 2017

### PR DESCRIPTION
**Pull request by Translator5**

### CODE REVIEW

**Comment by Translator5** [comment]
Updates tested on my mod-build works flawless
[Modlist](https://goo.gl/uWM24D) (116 esp's);
Changes to my loadorder are just;
> *116* German Text Patch.esp
> _115_ True_Lights_And_Darkness_1.1.esp

**Comment by Dragon-32** [comment]
There's something weird going on with text encoding, when I download this from Github and run it and my local copy of mlox_base through Winmerge:
Â£exa's Dwemer Alchemy V2 (EN).esm
TejÃ³n's Fatigue Effects - Blackout.esp
Â«Bitter Coast Sounds PluginÂ»
LothlÃ³rien Elf
LuminositÃ© Elementaire

Ah! My local copy is ANSI encoding, yours is UTF-8. Probably best to go for UTF-8 as standard then. Do you agree?

-----------------------------------------------------------
@Better Heads 2.0 [Gorg, Arathrax aka DarkSharp and Motoki]
```
;;Dragon32: Added by (I think) Translator5 without explanation
;;Dragon32: Checked Better Heads.esm against both ESMs in TESPCD, no conflict. Order rule removed.
;;Translator5: Mod have to replace faces of Tamriel Rebuild if using http://www.nexusmods.com/morrowind/mods/37001
;;[Order]
;;Tamriel_Data.esm
;;TR_Mainland.esm
;;Better Heads.esm
```
That mod you linked is a collection of meshes (.NIF files) only, no plugin. Looks like the way they did it was to take Better Heads meshes and rename the meshes to match the names of Tamriel Rebuilt meshes they wanted to replace.

Better Heads.esm defines body parts (BODY records) and assigns meshes to those body parts. Similarly TR has body parts defined and assigned to meshes.

Two ways to replace meshes used in game. One is plugin-based (change the BODY record to point to a different mesh) the other is replacing the meshes directly.

That mod uses the latter method. It doesn't touch BODY records so the relative load order of Better Heads and Tamriel Rebuilt has no bearing on whether or not the mod will work.

-----------------------------------------------------------
@Better Landscapes Stonewood Pass 1.0.1 [Mag1cWind0w, Melchior Dahrk]
```
;;Dragon32: Removed this as otherwise, to be consistent, we'd need to start adding a similar note for *every* landscape-affecting mod and *every* grass mod.
;;Translator5: I would keep it. Sth. I would like to know, maybe stb. else do have a word to it?
;;[Note]
;; "Using both cause not nice view in the Stonewood Pass!"
;;[All Better Landscapes Stonewood Pass (MD Edit).esp
;;     Ozzy's Grass - West Gash.esp]
```
Grass mods, like Ozzy's, shouldn't ever be loaded whilst playing Morrowind. They just define which meshes to use for particular types of grass and then their XYZ co-ordinates in exterior cells.

If someone does enable a grass plugin in-game then, with such a huge number of objects loaded by the game engine, their game will slow to a crawl. And (IIRC) some of them have collision so that'd be pretty hard to move around

Rather, grass mods should solely be used by MGE / MGE XE when generating its distant land. MGE / MGE XE then renders the meshes in game rather than the Morrowind engine.

So... we do not want people to load grass mods in game, just use them for MGE / MGE XE distant land generation.

e.g.
Ozzy's Grass Mods [Ozzy]
"This is ANIMATED grass, so DO NOT mark my file into Morrowind Launcher Menu if massive performance impact!"

-----------------------------------------------------------
@Herbalism for Purists 1.21 [Syclonix][Trr Kah]
```
[Order]
Vurt's Ashlands Overhaul.esp
Vurt's BC Tree Replacer II.esp
Vurt's Grazelands Unique Trees.ESP
Ozzy's Grass - Ascadian Isles.esp
Ozzy's Grass - Bitter Coast.esp
Ozzy's Grass - Grazelands.esp
Ozzy's Grass - Solstheim.esp
Ozzy's Grass - West Gash.esp
Syc_HerbalismforPurists.esp

[Order]
Vurt's Ashlands Overhaul.esp
Vurt's BC Tree Replacer II.esp
Vurt's Grazelands Unique Trees.ESP
Ozzy's Grass - Ascadian Isles.esp
Ozzy's Grass - Bitter Coast.esp
Ozzy's Grass - Grazelands.esp
Ozzy's Grass - Solstheim.esp
Ozzy's Grass - West Gash.esp
Syc_HerbalismforPurists.esp
Syc_HerbalismforPurists_DV.esp
```
See above for grass mods. As "Syc_HerbalismforPurists.esp" is in the first Order rule, the second Order rule could be:
```
[Order]
Vurt's Ashlands Overhaul.esp
Vurt's BC Tree Replacer II.esp
Vurt's Grazelands Unique Trees.ESP
Ozzy's Grass - Ascadian Isles.esp
Ozzy's Grass - Bitter Coast.esp
Ozzy's Grass - Grazelands.esp
Ozzy's Grass - Solstheim.esp
Ozzy's Grass - West Gash.esp
Syc_HerbalismforPurists_DV.esp
```
Or, IMO better:
```
[Order]
Vurt's Ashlands Overhaul.esp
Vurt's BC Tree Replacer II.esp
Vurt's Grazelands Unique Trees.ESP
Syc_HerbalismforPurists_DV.esp
```
It's possible to have grass plugins in a separate directory (IIRC). Personally I just have them with a far future Last Modified Date so they're right at the bottom in Wrye Mash. Means I can easily enable and disable them. If we start adding them into Order rules then they'd get buried in someone's load order and then easy enable / disable would be gone.

And people shouldn't be using them apart from for distant land generation.

Also, why are these two Order rules here? About all I could think of was CELL name conflicts between the German version and Vurt's mods but you've got the English version in one of these Order rules.

There's already an Order rule which does that (for DV) in: @Herbalism for Purists (DV) [Syclonix; Translation: Trr Kah]

-----------------------------------------------------------
@Morrowind Creatures Flying Tweaks [Amenophis]
```
;;It makes every creature setted as a flying-creature to fly - so should be loaded after all mods containing flying creature!
;;Translator5: (Ref. https://forum.openmw.org/viewtopic.php?t=4041 )
```
Oh! Looking at the mod it modifies Ancestor Ghost and Winged Twilight, think there're a number of other mods (Creatures for one) which would conflict but as it's only been downloaded 6 times I won't spend any time on it.

-----------------------------------------------------------
@New Beast Bodies 3.3 [LizTail]
```
;;Dragon32: Added by Translator5; "MK_Khajiit.esp" is from MacKom's "MacKoms Khajiit". No idea why added in here. If someone is going to load two Khajiit replacer mods then mlox isn't going to help them. That way lies madness, already wishing I hadn't done it for the Herbalism mods et al. Removed rule.
;;Translator5: You're sure? - If so, you underestimate its "users"!!!
```
If you want to do it, be my guest. But don't bury such a rule in a set of rules for a specific mod. Rather create a new category and have a conflict rule or what have you for all the various beast body replacers. Ensure you get all the ones included in mlox_base.txt or it'll look weird.

See these for the template to follow:
@Dark Brotherhood delay mods [Various]
@Herbalism mods [Various]
@Magicka cost reduction mods [Various]
@Magicka regeneration mods [Various]

-----------------------------------------------------------
@Province: Cyrodiil 01 [ProvinceCyrodiil]
```
[Order]
PC_Stirk_v<VER>.ESP
PC_Stirk_Grass.ESP
```
See previous for my thoughts on grass mods.

-----------------------------------------------------------
@Silt Striders 1.16 [abot]
```
;;there is no conflict between the SiltStriders and the Tamriel Rebuild project, it is just a suggestion! You are free to use both mods non-communicating between
[Note]
 "IF YOU HAVE TAMRIEL REBUILT INSTALLED, LOAD ONLY abotSiltStridersTR.esp"
 (Ref: "abotSiltStriders.txt")
[All abotSiltStriders.esp
	 [ANY TR_Mainland.esm
		  Tamriel_Data.esm
		  TR_Data.esm]]
```
I just fail to see why someone would load Tamriel Rebuilt and Silt Striders but purposefully not load a TR-compatible version of Silt Striders. This *is* a Conflict rule in mlox's parlance but it's more of a "Hey! Stupid!" rule. If the text of Conflict rules was highlighted in yellow then it'd stand out even more. I think EmperorArthur is working on that.

Also, the way you've got this rule written with the ANY means someone running SHOTN or PC would see this Note even without running Tamriel Rebuilt. They'd have "Tamriel_Data.esm" which would trigger the Note.

If you're insistent on changing this to a Note then I'd suggest going with:
```
[Note]
 !! "IF YOU HAVE TAMRIEL REBUILT INSTALLED, LOAD ONLY abotSiltStridersTR.esp"
 !! (Ref: "abotSiltStriders.txt")
[All abotSiltStriders.esp
     TR_Mainland.esm]
```
```
;; delete this following rule as soon abot updates his mod name for TR normally
[Requires]
 "IF YOU HAVE TAMRIEL REBUILT 1612 or newer INSTALLED, LOAD [...] abotSiltStridersTR1612.esp"
 (Ref: "abotSiltStriders.txt")
abotSiltStridersTR1612.esp
[ALL TR_Mainland.esm
     Tamriel_Data.esm]
```
This looks like it's from a later version than 1.16, bump the version number in the section header to "@Silt Striders 1.18 [abot]" (assume it's 1.18) so we know not to look at this mod again until / unless it's updated.

I'd suggest amending the first Conflict rule to:
```
[Conflict]
 Only use one plugin:
  abotSiltStridersTR1612.esp - If you use Tamriel Rebuilt 1612 or newer.
  abotSiltStridersTR.esp - If you use an earlier version of Tamriel Rebuilt.
  abotSiltStriders.esp  - If you do not.
 (Ref: "abotSiltStriders.txt")
abotSiltStriders.esp
abotSiltStridersTR.esp
abotSiltStridersTR1612.esp
```
This
```
[Requires]
 "IF YOU HAVE TAMRIEL REBUILT INSTALLED, LOAD [...] abotSiltStridersTR.esp"
 (Ref: "abotSiltStriders.txt")
abotSiltStridersTR.esp
[ALL TR_Mainland.esm
     [ANY TR_Data.esm
          Tamriel_Data.esm]]
```
Can just be
```
[Requires]
 "IF YOU HAVE TAMRIEL REBUILT INSTALLED, LOAD [...] abotSiltStridersTR.esp"
 (Ref: "abotSiltStriders.txt")
[ANY abotSiltStridersTR.esp
     abotSiltStridersTR1612.esp]
TR_Mainland.esm
```
As you need a Data ESM to load TR_Mainland.

This mod's rules need updating to include the new "abotSiltStridersTR1612.esp":
@Julan Real Time Transport Patch [abot]

-----------------------------------------------------------
@Skyrim: Home of the Nords 02 [SHOTN]
```
[Order]
Sky_Main.esp
Sky_Main_Grass.esp
```
See previous for my thoughts on grass mods.

-----------------------------------------------------------
@The Zone [Tarazaurus Rex]

When ordering mods in mlox_base.txt I generally try avoid common English words like "The" and "A" when putting the mod rules in alphabetical order. That's why this was under "Z"

**Comment by Dragon-32** [comment]
Run the new rules against the 403 mod lists in:
mlox\test\userfiles

(That's what they're there for)
No unintended messages being shown.

**Comment by Dragon-32** [comment]
Now what?

I'm going away for a fortnight on Thursday. I've a few changes on my side (mainly Morrowind Rebirth) I'd like to get into mlox_base.txt and there's a few changes in my big post just up there which would be worthwhile to make.

**Comment by EmperorArthur** [comment]
@Translator5 @Dragon-32 
Do both of you think this is ready for merging?

**Comment by EmperorArthur** [comment]
Sleight change of plans.

Cleaning everything up for a merge is taking a little bit of time.  Since this request relies on @Dragon-32's changes I think it would be easier to merge those first.  As soon as @Dragon-32 approves that one I'll get to work making git happy about this one.

**Comment by Dragon-32** [comment]
Thanks EmperorArthur, appreciated :)

I had another thought about these rules:
@herbalism for Purists 1.21 [Syclonix][Trr Kah]
```
[Order]
Vurt's Ashlands Overhaul.esp
Vurt's BC Tree Replacer II.esp
Vurt's Grazelands Unique Trees.ESP
Ozzy's Grass - Ascadian Isles.esp
Ozzy's Grass - Bitter Coast.esp
Ozzy's Grass - Grazelands.esp
Ozzy's Grass - Solstheim.esp
Ozzy's Grass - West Gash.esp
Syc_HerbalismforPurists.esp
```
They're basically forcing a fixed load order onto Vurt's three mods which I don't think is warranted.

If they're actually needed then I'd say to split them up unto 6 (3 for English and 3 for DV), like:
```
[Order]
Vurt's Ashlands Overhaul.esp
Syc_HerbalismforPurists.esp
```
As per previous comments I've dropped the grass mods.

**Comment by EmperorArthur** [comment]
This pull is now closed.

Please see Pull #13 for all of @Translator5's changes.

**Comment by Translator5** [comment]
@Dragon-32 
I've changes it to UTF-8
---
> Grass mods, like Ozzy's, shouldn't ever be loaded whilst playing Morrowind.

:smile:  - im playing with them :laughing: 

---
@herbalism for Purists 1.21
> See above for grass mods. As "Syc_HerbalismforPurists.esp" is in the first Order rule, ...

soo much people just enable both languages to be sure the mod is working at all!
I dont think we should steal them the possibility to sort mods properly

> About all I could think of was CELL name conflicts between the German version and Vurt's mods but you've got the English version in one of these Order rules.

sorry but i don not know - will have a look and give my statement later

---
@Morrowind Creatures Flying Tweaks
> I won't spend any time on it.

:smile: I will do it - as long it is not that big it do not hurt i think

**Pull request closed without merging**
