### PR TITLE
Prepare for the next release

### PR DESCRIPTION
**Pull request by EmperorArthur**
They say perfect is the enemy of good enough, and that's certainly true here.

While there may be one or two things before the next release, this change contains all the big parts. 
 Here's a rambling explanation for what's been happening, and where things are right now.  If you have any comments or suggestions, I'd be glad to hear them.

## Morrowind.ini writing:
Whenever the load order is saved, the config file (Morrowind.ini) has the new order saved to it.  This will remove any plugins that were in the file, but were not found in the data directory.

OpenMW users won't have to touch the original Morrowind, and can just import the updated Morrowind.ini to get a nice sorted plugin list.

## Use resources.py to keep track of all external files
It's not perfect, but does help simplify some of the code.

## gave the code a once over with `pylint`
It's a nice tool to highlight potential problem areas.  Once you disable the hundreds of warnings about not following the [python style guide](https://www.python.org/dev/peps/pep-0008/) it's actually useful in helping to catch errors before the code crashes on a user.

## Transition to argparse (re-wrote most of the command line code)
`pylint` really didn't like the old method of getting user arguments.  It worked great, but honestly I just wanted an excuse to try the python method instead of the C like way we were doing things.

The help screen looks different, but all arguments should work the same as always.

## What didn't happen
I had the neat idea of trying to include data in the application itself, then statically compile the whole thing to a single exe.  Unfortunately, the python compilers were not cooperating.

First I tried `nuitka`, which works, but is slow and produces quite a few ".dll" and ".pyd" files that need to be bundled with the application.  I'm leaning towards this method anyways, since it has some advantages I'll get to in a minute.

Next I tried `pyinstaller`.  It's better, but what it's really doing is creating a temporary directory that it's extracting all those ".dll" files into.  This is a problem since mlox looks for the database file in the directory it's called from.  Since that ends up being a temporary directory, it can never find the database.  In practice, it means the updater runs every time mlox.exe is executed.  It also means we can't abuse the updater.

I haven't tried `py2exe` yet.  That's next on my list, but it's going to have some long term issues.  Specifically I'm hoping to move mlox to Python 3 in the future, and py2exe only supports Python 2.

## Abusing the updater
Here's something you should be aware of.  mlox currently has an interesting "feature" where anything in mlox-data.7z overwrites whatever is in the directory it's extracted in.  That means mlox_base.txt is kept up to date.  However, it's extremely easy to change that to update mlox.exe directly.  I don't know if windows allows that sort of behavior, but it's certainly something to be aware of.

## Future plans for dealing with `pyinstaller` and similar issues.
mlox has a fundamental problem.  It's designed to modify things that normally sit in "Program Files."  A directory that windows requires elevated permissions to touch.  An option is to have mlox store things like its database in the users AppData or appropriate directory.  There's even a [python module](https://pypi.python.org/pypi/appdirs) for handling just that.  The only two downsides are mlox becomes a bit less portable\*, and we can't abuse the updater trick to update mlox in the future. 

My suggestion would be to implement some sort of version check when reading mlox_base.txt, and prompting the user to update if a new version of mlox is available.

\* Users would have to open an estoric directory to use 'mlox_user.txt', but let's be honest, almost no one uses that file.

### CODE REVIEW

**Comment by Dragon-32** [comment]
**Morrowind.ini writing**
Woah. OpenMW support? Nice one. I infer mlox directly messing with openmw.cfg isn't on the cards though?

**Transition to argparse (re-wrote most of the command line code)**
When testing rules I use this:
```
FOR %%f in ("C:\Games\Bethesda Softworks\Morrowind\mlox\test\userfiles\*.txt") DO mlox.pyo -wf -n "%%f" >>TestOutput.txt
```
Which returns the output for the ~400 user mod lists in that directory. Actually I use the command twice, one without the new rules in mlox_user and one with. Then diff the two files.

So...

On a selfish level as long as those two remain as options (use a file; skip download check) it's good. If syntax changes somewhat (doesn't sound like it will) that's all cool too, as long as it's written down somewhere :)

I think most end users use the GUI. I've used some other command line options before but that's my regular use case.


**Abusing the updater**
Really don't know how Windows would handle that. I think attempting to update the .exe in that way would cause an error.

mlox.exe is running, invokes 7za.exe to extract another copy of mlox.exe over itself --> "file in use, can't overwrite" or similar. I think.


**Future plans for dealing with pyinstaller and similar issues.**
I think you could replace "mlox" in that first sentence with "Morrowind". It's a pre-Vista game so all that UAC and folder virtualisation shenanigans wasn't in place. E.g. morrowind.exe writes to morrowind.ini, which is stored in the protected Program Files (or these days for 64bit OSs in Program Files(x86) is you want to be pedantic) directory.

Basic advice for installing games of Morrowind's vintage is to install it outside of Program Files / Program Files(x86)

That said, if we're talking future plans... Does mlox need to be in the Morrowind directory tree? It could be installed in Program Files, read the Morrowind install directory from the Registry and use that (with some kind of an Options dialog to repoint to a different directory to cope with multiple installs)

Anyway.

C:\ProgramData is a hidden directory which looks like it's used for some of these kinds of files, like C:\Users\<account>\AppData (then there's Local, LocalLow and Roaming sub-directories)

If mlox_user.txt was moved out of the main mlox directory then there'd need to be some kind if GUI widget to either open that directory or bring up the text editor to edit it. Whilst it's not commonly used a general troubleshooting step I've suggested to some people is to use [NearEnd] in mlox_user.txt

So exposing that somehow to the end-user would be important.

Your update suggestion for the .exe is a good one. Presumably there's a way to scrape the Releases page here for latest version number? I think an auto-updater is too much hassle. Some kind of dismissable dialog box (New version available click here to download --> open GitHub in browser) would be the way to go

**Comment by EmperorArthur** [comment]
Sorry for the late reply.  Evacuating has taken most of my time recently.  Actually, since I'm still evacuated, who knows when I'll be on next.

> I infer mlox directly messing with openmw.cfg isn't on the cards though?

I was having a problem finding where the file was stored, but have since found [appdirs](https://pypi.python.org/pypi/appdirs/1.4.0).  If that works, modifying the code to handle openmw.cfg shouldn't be too hard.

> On a selfish level as long as those two remain as options (use a file; skip download check) it's good. If syntax changes somewhat (doesn't sound like it will) that's all cool too, as long as it's written down somewhere :)

There's a minor change.  You might have to do `mlox -wf <file_1> <file_2> -n` instead.  The reason why is if we add something like `--game-directory <dir>` the program could be confused if everything was at the end.

> Really don't know how Windows would handle that. I think attempting to update the .exe in that way would cause an error.

> mlox.exe is running, invokes 7za.exe to extract another copy of mlox.exe over itself --> "file in use, can't overwrite" or similar. I think.

True, I forgot that windows does not handle that sort of thing the way Linux does.  Ah well, it was an idea.

> C:\ProgramData is a hidden directory which looks like it's used for some of these kinds of files, like C:\Users<account>\AppData (then there's Local, LocalLow and Roaming sub-directories)

Fortunately, [appdirs](https://pypi.python.org/pypi/appdirs/1.4.0) handles that detail for us.  It even transparently handles Linux.  The more difficult part is just telling the user where the folder is.  Next release, probably.

> I think an auto-updater is too much hassle. Some kind of dismissable dialog box (New version available click here to download --> open GitHub in browser) would be the way to go

I have an idea on that.  The program already parses the version string from the data file.  We could put all the relevant information there.

Alright.  I'm going to go ahead and merge this thing, and get the release going.

**Comment by Dragon-32** [comment]
Oh you're in the track of Irma? Yikes. Hope everything goes as well as it can do.

With the work-on-a-file switch, looks like I can still pass it the filename from the variable in the batch file so it's all good.

**Comment by EmperorArthur** [comment]
Glad to hear it still works.  I'm no longer evacuated, but now it's making up for a weeks worth of work.

**Pull request merged**
