### PR TITLE
Update mlox_base rules

### PR DESCRIPTION
**Pull request by yooksi**
Included almost all of Abot's user rules *(avoiding more monolithic ones)*, Corsair's order rules as well as some other community additions from the Discord server.

### CODE REVIEW

**Comment by EmperorArthur** [comment]
Hey, thanks for this PR.

It looks like you have combined three different changes into one Pull Request.  I'd appreciate it if you would please break those out into separate ones.
* The 'qtGui.py' one should be pretty quick to confirm that it works.
* The 'mlox_base' changes will take a bit to read through, and since the actual file link is a SourceForge file hosting I have to manually upload those changes. (side note, but if you know an updater python module that's not me rolling my own please let me know.)
* The 'MWSE-LUA' script checks are going to take me a bit to confirm what they're doing.  Plus, the command needs to be documented. (another side note, but I'm debating the pros and cons of switching to an XML 'mlox_base' or other less custom format, every extra function added makes this harder to do, especially if it isn't used.)

As I said, I really appreciate the work.  The only reason I haven't made another release with this Qt5 GUI is because I'm not sure how to package it for Windows.

**Comment by yooksi** [comment]
@EmperorArthur Thank you for coming back to this project to respond. I will split this into two pull requests. You should really come and talk to the G7 and Null on Discord (mwse channel) about the future development of app functionality, I am just writing base rules.

**Comment by EmperorArthur** [comment]
Sorry it's taking me so long to review this.  I'm going to make time this weekend to review this and actually write up what it takes to upload a new 'mlox_base.txt' file.

**Comment by yooksi** [comment]
@EmperorArthur Alright, thank you for not forgetting about this.

**Comment by EmperorArthur** [comment]
Looks good.
In the future, I'd appreciate it if you would please update the version to the date of your last commit.

**Pull request merged**
