### PR TITLE
Translator5's mlox_base.txt modifications

### PR DESCRIPTION
**Pull request by EmperorArthur**
So, I went through all of Translator5's patches and rebased them on top of Dragon-32's work.

There was quite a bit that Dragon-32 had already done, so was left out of the individual patches. 
 Everything should be correct, but I highly advise double checking that all of these do work.

Once this is merged I highly suggest that both @Translator5 and @Dragon-32 make a copy of any work you've done and run:
```
git fetch upstream
git checkout master
git reset --hard upstream/master
```

Edit:  Here's a description of what that code is doing:  https://forum.freecodecamp.org/t/override-local-files-with-git-pull/13216

### CODE REVIEW

**Comment by Translator5** [comment]
fetch, checkout, hard-reset - done
By the way I think some of my edits are based on @Dragon-32's work - hope it will not conflict

I'm actually having a look at the differences - but GitKraken is really going crazy "whyever"

**Comment by EmperorArthur** [comment]
Ok, if that's everything, now I'm just waiting on @Dragon-32 to give the final go ahead.

Once this is merged, I'll prep a release file for all the users.

**Comment by EmperorArthur** [comment]
Pinging @Dragon-32 

Do these look good to you?
If so, I will merge them.

**Comment by Dragon-32** [comment]
abot's just uploaded "ab01TR_Travels" - http://www.nexusmods.com/morrowind/mods/42267/

**Comment by Translator5** [comment]
> ;; @Magic Diversity 1.0 [Arkann][volia27]
> 
> to
> 
> ;; @Magic Diversity 1.1 [Arkann][volia27]
>...

As already mentioned anywhere, 1.1 is not the version of Arkann, but volia27 and just contains the russian translation.

EDIT: 
>ANY predicate doesn't work consistently for Order rules (see a previous Commit discussion)
Need to change this and all the other Order rules

... hmm, yeah than it have to be that way, I think.

**Comment by EmperorArthur** [comment]
Ok.  @Dragon-32 I've just merged the latest changes by @Translator5 into this pull request.

How do things look now?

**Comment by Translator5** [comment]
Fixed the last few ANY-Order rules (I think so), have to be merged.

About the error - I actually do not have a Idea what is going on there! :laughing:

**Comment by EmperorArthur** [comment]
Data files are now uploaded.  Everyone should see the changes the next time they open mlox.

**Pull request merged**
