### PR TITLE
Changes to DESC rules because of regular expression error

### PR DESCRIPTION
**Pull request by Dragon-32**
Fix for Issue #14 

Asked for a review as I'd like to double-check I'm doing this right

### CODE REVIEW

**Comment by EmperorArthur** [comment]
I think it's working correctly, but the parser is black magic to me.
Seriously, I spent quite a while trying to come up with a minimal test case (mlox_base.txt, and appropriate file) before giving up.  The parser just doesn't seem to crash with the old version.

Telling mlox to look at a file with 'BTB - Equipment.esp' and 'LeftGloves_Addon_v2.esp' gave me this result (note, the \* are still there, but Github is interpreting them as markdown):

> [CONFLICT]
 > '[DESC !/*Edited by Tooplex for MGSO Compatibility*/ BTB - Equipment.esp]'
 > 'LeftGloves_Addon_v2.esp'
 | Tooplex has created a version of the "BTB - Equipment" plugin from "BTB's Game Improvements" which merges "Left Gloves Addon" by Alaisiagae.
 | Download "BTBs Game Improvements - MGSO Compatibility" from Morrowind Nexus - http://www.nexusmods.com/morrowind/mods/43522/
 | (Ref: "BTBGI - MGSO Compatability V1.5-43522-1-5.rar\Readme.txt")
[CONFLICT]
 > [ALL
 >   '[DESC /*Edited by Tooplex for MGSO Compatibility*/ BTB - Equipment.esp]',
 >   '[SIZE 352688 BTB - Equipment.esp]']
 > 'LeftGloves_Addon_v2.esp'
 | Tooplex's version of the "BTB - Equipment" plugin from "BTB's Game Improvements" merges "Left Gloves Addon" by Alaisiagae.
 | (Ref: "BTBGI - MGSO Compatability V1.5-43522-1-5.rar\Readme.txt")

**Comment by Dragon-32** [comment]
Minimal test case would be these installed in Data Files and active in morrowind.ini. Link for Sir Luthor's Tools download on MMH in Issue #14:
Morrowind.esm
SirLuthor-Tools.esp

Then run mlox with currently published mlox_base.txt (not these changes)

You need to have the plugin itself in Data Files, just passing a mod list doesn't get the parser running, which is why it never triggered when I checked the submission against the approx. 400 mod lists I've got locally in mlox\test\userfiles

**Comment by Dragon-32** [comment]
Reason for asking for a review was I've beaten various repositories with the rebase stick and just wanted a second pair of eyes check that I hadn't messed up anything (again).

**Comment by EmperorArthur** [comment]
Incidentally, this is what me pressing the merge button from github does, instead of doing it locally.

**Comment by Dragon-32** [comment]
Thanks for checking, and for uploading the new .7z

**Pull request merged**
